version: '3'
services:
  productpage:
    build:
      context: src/productpage
    ports:
      - '9080:9080'
  details:
    build:
      context: src/details
    ports:
      - '9081:9081'
  ratings:
    build:
      context: src/ratings
    ports:
      - '9082:9082'
  reviews:
    build:
      context: src/reviews
    ports:
      - '9083:9083'