version: '3'
services:
  productpage:
    build:
      dockerfile: src/productpage/Dockerfile
      context: .
    ports:
      - '9080:9080'
  details:
    build:
      dockerfile: src/details/Dockerfile
      context: .
    ports:
      - '9081:9081'
  ratings:
    build:
      dockerfile: src/ratings/Dockerfile
      context: .
    ports:
      - '9082:9082'
  reviews:
    build:
      dockerfile: src/reviews/Dockerfile
      context: .
    ports:
      - '9083:9083'