version: '3'

services:
  productpage:
    build:
      context: src/productpage
      args:
        - flood_factor=100
    ports:
      - '9080:9080'
    links:
      - mongodb
      - mysql
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017
      - MYSQL_DB_URL=jdbc:mysql://mysql:3306/bookinfo
      - MYSQL_DB_USER=mysql
      - MYSQL_DB_PASSWORD=root

  details:
    build:
      context: src/details
      args:
        - service_version=v2
        - enable_external_book_service=true
    ports:
      - '9081:9080'
    links:
      - mongodb
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017

  ratings:
    build:
      context: src/ratings
      args:
        - service_version=v2
    ports:
      - '9082:9080'
    links:
      - mongodb
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017

  reviews:
    build:
      context: src/reviews
      args:
        - service_version=v3
        - enable_ratings=true
        - star_color=red
    ports:
      - '9083:9080'

  mongodb:
    build:
      context: src/mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=root

  mysql:
    build:
      context: src/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root